### PR TITLE
chore: upgrade node.js version

### PR DESCRIPTION
**Pull request by chenquan**
Node 12 has been out of support since April 2022, as a result we have started the deprecation process of Node 12 for GitHub Actions. We plan to migrate all actions to run on Node16 by Summer 2023. We will monitor the progress of the migration and listen to the community for how things are going before we define a final date. To raise awareness of the upcoming change, we are adding a warning into workflows which contain Actions running on Node 12. This will come into effect starting on September 27th.

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

### CODE REVIEW

**Comment by chenquan** [comment]
@tomsun28  PTAL

**Review by tomsun28 — APPROVED** [review]
👍👍 thanks！LGTM

**Comment by chenquan** [comment]
> 👍👍 thanks！LGTM

@tomsun28 
Hi! When will the latest version be released?

**Comment by tomsun28** [comment]
@chenquan HI, Try to release this week.

**Comment by tomsun28** [comment]
@all-contributors please add @chenquan for code

**Pull request merged**
